package com.args;

import com.common.Annotation;

import java.io.Serializable;

public class MHapViewArgs implements Serializable {
    @Annotation("input file, mhap.gz format, generated by mHapTools and indexed")
    public String mhapPath = "";
    @Annotation("genomic CpG file, gz format and Indexed")
    public String cpgPath = "";
    @Annotation("one region, in the format of chr:start-end")
    public String region = "";
    @Annotation("bed file, one query region per line")
    public String bedPath;
    @Annotation("output file")
    public String tag = "";
    @Annotation("output format,pdf or png [pdf]")
    public String outFormat = "pdf";
    @Annotation("plus,minus,both [both]")
    public String strand = "both";

    public String getMhapPath() {
        return mhapPath;
    }

    public void setMhapPath(String mhapPath) {
        this.mhapPath = mhapPath;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getBedPath() {
        return bedPath;
    }

    public void setBedPath(String bedPath) {
        this.bedPath = bedPath;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getOutFormat() {
        return outFormat;
    }

    public void setOutFormat(String outFormat) {
        this.outFormat = outFormat;
    }

    public String getStrand() {
        return strand;
    }

    public void setStrand(String strand) {
        this.strand = strand;
    }

}
