package com.args;

import java.io.Serializable;

public class MHBDiscoveryArgs implements Serializable {
    public String mHapPath = ""; // input file,mhap.gz format,generated by mHapTools and indexed
    public String cpgPath = ""; // genomic CpG file, gz format and indexed
    public String region = ""; // one region, in the format of chr:start-end
    public String bedPath = ""; // input BED file
    public Integer window = 5; // Size of core window
    public Double r2 = 0.5; // R square cutoff
    public Double pvalue = 0.05; // P value cutoff
    public String outputDir = ""; // output directory, created in advance
    public String tag = "MHBDiscovery_out"; // prefix of the output file(s)
    public boolean qcFlag = false; // whether output matrics for QC

    public String getmHapPath() {
        return mHapPath;
    }

    public void setmHapPath(String mHapPath) {
        this.mHapPath = mHapPath;
    }

    public String getBedPath() {
        return bedPath;
    }

    public void setBedPath(String bedPath) {
        this.bedPath = bedPath;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public Integer getWindow() {
        return window;
    }

    public void setWindow(Integer window) {
        this.window = window;
    }

    public Double getR2() {
        return r2;
    }

    public void setR2(Double r2) {
        this.r2 = r2;
    }

    public Double getPvalue() {
        return pvalue;
    }

    public void setPvalue(Double pvalue) {
        this.pvalue = pvalue;
    }

    public String getOutputDir() {
        return outputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public boolean isQcFlag() {
        return qcFlag;
    }

    public void setQcFlag(boolean qcFlag) {
        this.qcFlag = qcFlag;
    }
}
