package com.args;

import com.common.Annotation;

import java.io.Serializable;

public class StatArgs implements Serializable {
    @Annotation("mHap-level metrics, including MM, PDR, CHALM, MHL, MCR, MBS, Entropy and R2 [None]")
    public String metrics = ""; //
    @Annotation("input file,mhap.gz format,generated by mHapTools and indexed")
    public String mhapPath = ""; //
    @Annotation("genomic CpG file, gz format and indexed")
    public String cpgPath = ""; //
    @Annotation("one region, in the format of chr:start-end")
    public String region = ""; //
    @Annotation("bed file, one query region per line")
    public String bedPath; //
    @Annotation("output file")
    public String outputFile = ""; //
    @Annotation("minimum k-mer length for MHL [1]")
    public Integer minK = 1; //
    @Annotation("maximum k-mer length for MHL [10]")
    public Integer maxK = 10; //
    @Annotation("k-mer length for entropy, PDR, and CHALM, can be 3, 4, or 5 [4]")
    public Integer K = 4; //
    @Annotation("plus,minus,both [both]")
    public String strand = "both"; //
    @Annotation("indicates whether only keep CpGs in the defined region")
    public Boolean cutReads = false; //
    @Annotation("minimal number of reads that cover two CpGs for R2 calculation [20]")
    public Integer r2Cov = 20; //

    public String getMetrics() {
        return metrics;
    }

    public void setMetrics(String metrics) {
        this.metrics = metrics;
    }

    public String getMhapPath() {
        return mhapPath;
    }

    public void setMhapPath(String mhapPath) {
        this.mhapPath = mhapPath;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getBedPath() {
        return bedPath;
    }

    public void setBedPath(String bedPath) {
        this.bedPath = bedPath;
    }

    public String getOutputFile() {
        return outputFile;
    }

    public void setOutputFile(String outputFile) {
        this.outputFile = outputFile;
    }

    public Integer getMinK() {
        return minK;
    }

    public void setMinK(Integer minK) {
        this.minK = minK;
    }

    public Integer getMaxK() {
        return maxK;
    }

    public void setMaxK(Integer maxK) {
        this.maxK = maxK;
    }

    public Integer getK() {
        return K;
    }

    public void setK(Integer k) {
        K = k;
    }

    public String getStrand() {
        return strand;
    }

    public void setStrand(String strand) {
        this.strand = strand;
    }

    public Boolean getCutReads() {
        return cutReads;
    }

    public void setCutReads(Boolean cutReads) {
        this.cutReads = cutReads;
    }

    public Integer getR2Cov() {
        return r2Cov;
    }

    public void setR2Cov(Integer r2Cov) {
        this.r2Cov = r2Cov;
    }
}
