package com.args;

import java.io.Serializable;

public class StatArgs implements Serializable {
    public String metrics = ""; // mHap-level metrics, including MM, PDR, CHALM, MHL, MCR, MBS, Entropy and R2 [None]
    public String mhapPath = ""; // input file,mhap.gz format,generated by mHapTools and indexed
    public String cpgPath = ""; // genomic CpG file, gz format and indexed
    public String region = ""; // one region, in the format of chr:start-end
    public String bedPath; // input BED file
    public String outputFile = ""; // output file
    public Integer minK = 1; // minimum k-mer length for MHL [1]
    public Integer maxK = 10; // maximum k-mer length for MHL [10]
    public Integer K = 4; // k-mer length for entropy, PDR, and CHALM, can be 3, 4, or 5 [4]
    public String strand = "both"; // plus,minus,both [both]
    public Boolean cutReads = false; // indicates whether only keep CpGs in the defined region
    public Integer cutOff = 0; // cutoff reads count for R2

    public String getMetrics() {
        return metrics;
    }

    public void setMetrics(String metrics) {
        this.metrics = metrics;
    }

    public String getMhapPath() {
        return mhapPath;
    }

    public void setMhapPath(String mhapPath) {
        this.mhapPath = mhapPath;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getBedPath() {
        return bedPath;
    }

    public void setBedPath(String bedPath) {
        this.bedPath = bedPath;
    }

    public String getOutputFile() {
        return outputFile;
    }

    public void setOutputFile(String outputFile) {
        this.outputFile = outputFile;
    }

    public Integer getMinK() {
        return minK;
    }

    public void setMinK(Integer minK) {
        this.minK = minK;
    }

    public Integer getMaxK() {
        return maxK;
    }

    public void setMaxK(Integer maxK) {
        this.maxK = maxK;
    }

    public Integer getK() {
        return K;
    }

    public void setK(Integer k) {
        K = k;
    }

    public String getStrand() {
        return strand;
    }

    public void setStrand(String strand) {
        this.strand = strand;
    }

    public Boolean getCutReads() {
        return cutReads;
    }

    public void setCutReads(Boolean cutReads) {
        this.cutReads = cutReads;
    }

    public Integer getCutOff() {
        return cutOff;
    }

    public void setCutOff(Integer cutOff) {
        this.cutOff = cutOff;
    }
}
