package com.args;

import java.io.Serializable;

public class TanghuluArgs implements Serializable {
    public String mhapPath = ""; // input file,mhap.gz format,generated by mHapTools and indexed
    public String cpgPath = ""; // genomic CpG file, gz format and indexed
    public String region = ""; // one region, in the format of chr:start-end
    public String outputFile = ""; // output file
    public String outFormat = "pdf"; // output format,pdf or png [pdf]
    public String strand = "both"; // plus,minus,both [both]
    public Integer maxReads = 50; // the max number of reads to plot [50]
    public Integer maxLength = 2000; // the max length of region to plot [2000]
    public Boolean merge = false; // indicates whether identical mHaps should be merged
    public Boolean simulation = false; // indicates whether mHaps should be simulated
    public Boolean cutReads = false; // indicates whether only keep CpGs in the defined region

    public String getMhapPath() {
        return mhapPath;
    }

    public void setMhapPath(String mhapPath) {
        this.mhapPath = mhapPath;
    }

    public String getCpgPath() {
        return cpgPath;
    }

    public void setCpgPath(String cpgPath) {
        this.cpgPath = cpgPath;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getOutputFile() {
        return outputFile;
    }

    public void setOutputFile(String outputFile) {
        this.outputFile = outputFile;
    }

    public String getOutFormat() {
        return outFormat;
    }

    public void setOutFormat(String outFormat) {
        this.outFormat = outFormat;
    }

    public String getStrand() {
        return strand;
    }

    public void setStrand(String strand) {
        this.strand = strand;
    }

    public Integer getMaxReads() {
        return maxReads;
    }

    public void setMaxReads(Integer maxReads) {
        this.maxReads = maxReads;
    }

    public Integer getMaxLength() {
        return maxLength;
    }

    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
    }

    public Boolean getMerge() {
        return merge;
    }

    public void setMerge(Boolean merge) {
        this.merge = merge;
    }

    public Boolean getSimulation() {
        return simulation;
    }

    public void setSimulation(Boolean simulation) {
        this.simulation = simulation;
    }

    public Boolean getCutReads() {
        return cutReads;
    }

    public void setCutReads(Boolean cutReads) {
        this.cutReads = cutReads;
    }

}
